spring:
  application:
    name: training-program-backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: 612520
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  mail:
    host: smtp.qq.com
    username: 1366401799@qq.com
    password: "agjhppkqilybhafc"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
        "mail.smtp.connectiontimeout": 5000
        "mail.smtp.timeout": 3000
        "mail.smtp.writetimeout": 5000
        "mail.smtp.auth": true
        "mail.smtp.starttls.enable": true
        "mail.smtp.starttls.required": true
  session:
    store-type: jdbc


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  path: E:\Work\Project\IDEAProject\training-program-backend\images\
server:
  address: 0.0.0.0 #允许局域网访问
  servlet:
    session:
      timeout: 30m